LOCAL  Red, wPre

IF ! FILE("NABPROD.DBF")
	CREATE RADNA
	STORE "sif       N13 " TO POLJE1
	STORE "naz       C30 " TO POLJE2
	STORE "datn      D8  " TO POLJE3
	STORE "koln      N123" TO POLJE4
	STORE "cenn      N122" TO POLJE5
	STORE "datp      D8  " TO POLJE6
	STORE "kolp      N123" TO POLJE7
	STORE "cenp      N122" TO POLJE8
	FOR I = 1 TO 8
		IF I < 10
			STORE  STR(I,1) TO BROJ
		ELSE
			STORE  STR(I,2) TO BROJ
		ENDIF
		P1 = "POLJE" + BROJ
		APPEND BLANK
		REPLACE FIELD_NAME WITH SUBSTR(&P1,1,10)
		REPLACE FIELD_TYPE WITH SUBSTR(&P1,11,1)
		REPLACE FIELD_LEN WITH VAL(SUBSTR(&P1,12,2))
		REPLACE FIELD_DEC WITH VAL(SUBSTR(&P1,14,1))
	NEXT I
	CREATE NABPROD FROM RADNA
	INDEX ON STR(SIF,13,0) + DTOS(DATN) TO NABPROD
	USE
	ERASE RADNA.DBF
ENDIF

IF File("dmpinsd.ntx")
	Erase dmpinsd.ntx
ENDIF

SELECT 0
USE DMPDAT
INDEX ON Str(dmpsif,13,0) + Dtos(dmpdat) TO dmpinsd
CLOSE DMPDAT

IF File("pazsd.ntx")
	Erase pazsd.ntx
ENDIF

SELECT 0
USE PAZDAT
INDEX ON Str(pazart,13,0) + Dtos(pazdat) TO pazsd
CLOSE PAZDAT

SELECT 0
USE DMPDAT INDEX DMPINSD

SELECT 0
USE NABPROD INDEX NABPROD
ZAP

SELECT 0
USE ARTPANE INDEX APINSIF,APINART

SELECT 0
USE PAZDAT INDEX PAZSD
SET FILTER TO SK = 0
GO TOP

SELECT ARTPANE
GO TOP

DO WHILE ! Eof()	&& ARTPANE IDEMO SLOG PO SLOG

	wPre = ARTSIF

	SELECT DMPDAT
	SEEK STR(ARTPANE->ARTSIF,13,0)
	IF Found()
		DO WHILE wPre = DMPSIF
			SELECT NABPROD
			APPEND BLANK
			REPLACE SIF WITH DMPDAT->DMPSIF
			REPLACE NAZ WITH DMPDAT->DMPNAZ
			REPLACE DATN WITH DMPDAT->DMPDAT
			REPLACE KOLN WITH DMPDAT->DMPKOL
			REPLACE CENN WITH Round(DMPDAT->DMPNC / DMPDAT->DMPKOL,2)

			SELECT DMPDAT
			SKIP
		ENDDO
	ENDIF

	* izasao iz jednog artikla u DMPDAT
    * sada ici i videti da li je prodavan
	SELECT PAZDAT
   SEEK STR(ARTPANE->ARTSIF,13,0)
   IF Found()
		DO WHILE wPre = PAZART
			SELECT NABPROD
			APPEND BLANK
			REPLACE SIF WITH PAZDAT->PAZART
			REPLACE DATN WITH PAZDAT->PAZDAT
			REPLACE DATP WITH PAZDAT->PAZDAT
			REPLACE KOLP WITH PAZDAT->PAZKOL
			REPLACE CENP WITH PAZDAT->PAZCDIN

			SELECT PAZDAT
			SKIP
		ENDDO
	ENDIF

	SELECT ARTPANE
	SKIP
ENDDO	&& Eof() ARTPANE


SET DEVICE TO PRINT
SET PRINT TO LPT1
SET PRINT ON

Red = 80
SELECT NABPROD
GO TOP

DO WHILE ! Eof()
	* odstampati slog za artikal
	IF Red > 65
		@ 2,5  SAY "NABAVLJENI I PRODATI ARTIKLI OD "
		@ 2,37 SAY Date()
		@ 2,48 SAY "DO "
		@ 2,51 SAY Date()
		@ 4,0  SAY "SIF.ART"
		@ 4,08 SAY "  NAZIV ARTIKLA"
		@ 4,24 SAY "DAT.NABAV."
		@ 4,35 SAY "NAB.KOLI"
		@ 4,44 SAY "PRO.KOLI"
		@ 4,53 SAY "DAT.PRODA."
		@ 4,64 SAY "NAB.KOLI"
		@ 4,73 SAY "PRO.KOLI"
		@ 5,0  SAY Replicate("-",80)
		Red = 6
	ENDIF

	@ Red,0 SAY Substr(Alltrim(Str(SIF,13,0)),1,7) PICTURE "9999999"
	@ Red,08 SAY Substr(NAZ,1,15)

	IF Empty(DATP)
		@ Red,24 SAY DATN
	ENDIF

	@ Red,35 SAY KOLN PICTURE "9999.999"
	@ Red,44 SAY CENN PICTURE "99999.99"
	@ Red,53 SAY DATP
	@ Red,64 SAY KOLP PICTURE "9999.999"
	@ Red,73 SAY CENP PICTURE "99999.99"
	Red = Red + 1

	SKIP
ENDDO

EJECT

SET DEVICE TO SCREEN
SET PRINT OFF
SET FILTER TO

CLOSE DATABASES

RETURN
