SELECT 0
USE KUMULUP
SELECT 0
USE PLACP INDEX PLACP

WOD   = Date()
WDO   = Date()
wz11  = Val("00000000.00")
wz21  = Val("00000000.00")
wz31  = Val("00000000.00")
wz41  = Val("00000000.00")
wz51  = Val("00000000.00")
wz61  = Val("00000000.00")
wz71  = Val("00000000.00")
wz81  = Val("00000000.00")
wz91  = Val("00000000.00")
wz101 = Val("00000000.00")
wz111 = Val("00000000.00")
wz121 = Val("00000000.00")
wz131 = Val("00000000.00")
wz141 = Val("00000000.00")
wz151 = Val("00000000.00")
wz161 = Val("00000000.00")
wz171 = Val("00000000.00")
wz181 = Val("00000000.00")
wz191 = Val("00000000.00")
wz201 = Val("00000000.00")
wz211 = Val("00000000.00")
wz221 = Val("00000000.00")

wz12  = Val("00000000.00")
wz22  = Val("00000000.00")
wz32  = Val("00000000.00")
wz42  = Val("00000000.00")
wz52  = Val("00000000.00")
wz62  = Val("00000000.00")
wz72  = Val("00000000.00")
wz82  = Val("00000000.00")
wz92  = Val("00000000.00")
wz102 = Val("00000000.00")
wz112 = Val("00000000.00")
wz122 = Val("00000000.00")
wz132 = Val("00000000.00")
wz142 = Val("00000000.00")
wz152 = Val("00000000.00")
wz162 = Val("00000000.00")
wz172 = Val("00000000.00")
wz182 = Val("00000000.00")
wz192 = Val("00000000.00")
wz202 = Val("00000000.00")
wz212 = Val("00000000.00")
wz222 = Val("00000000.00")

wz13  = Val("00000000.00")
wz23  = Val("00000000.00")
wz33  = Val("00000000.00")
wz43  = Val("00000000.00")
wz53  = Val("00000000.00")
wz63  = Val("00000000.00")
wz73  = Val("00000000.00")
wz83  = Val("00000000.00")
wz93  = Val("00000000.00")
wz103 = Val("00000000.00")
wz113 = Val("00000000.00")
wz123 = Val("00000000.00")
wz133 = Val("00000000.00")
wz143 = Val("00000000.00")
wz153 = Val("00000000.00")
wz163 = Val("00000000.00")
wz173 = Val("00000000.00")
wz183 = Val("00000000.00")
wz193 = Val("00000000.00")
wz203 = Val("00000000.00")
wz213 = Val("00000000.00")
wz223 = Val("00000000.00")

wz14  = Val("00000000.00")
wz24  = Val("00000000.00")
wz34  = Val("00000000.00")
wz44  = Val("00000000.00")
wz54  = Val("00000000.00")
wz64  = Val("00000000.00")
wz74  = Val("00000000.00")
wz84  = Val("00000000.00")
wz94  = Val("00000000.00")
wz104 = Val("00000000.00")
wz114 = Val("00000000.00")
wz124 = Val("00000000.00")
wz134 = Val("00000000.00")
wz144 = Val("00000000.00")
wz154 = Val("00000000.00")
wz164 = Val("00000000.00")
wz174 = Val("00000000.00")
wz184 = Val("00000000.00")
wz194 = Val("00000000.00")
wz204 = Val("00000000.00")
wz214 = Val("00000000.00")
wz224 = Val("00000000.00")

wz15  = Val("00000000.00")
wz25  = Val("00000000.00")
wz35  = Val("00000000.00")
wz45  = Val("00000000.00")
wz55  = Val("00000000.00")
wz65  = Val("00000000.00")
wz75  = Val("00000000.00")
wz85  = Val("00000000.00")
wz95  = Val("00000000.00")
wz105 = Val("00000000.00")
wz115 = Val("00000000.00")
wz125 = Val("00000000.00")
wz135 = Val("00000000.00")
wz145 = Val("00000000.00")
wz155 = Val("00000000.00")
wz165 = Val("00000000.00")
wz175 = Val("00000000.00")
wz185 = Val("00000000.00")
wz195 = Val("00000000.00")
wz205 = Val("00000000.00")
wz215 = Val("00000000.00")
wz225 = Val("00000000.00")

wz16  = Val("00000000.00")
wz26  = Val("00000000.00")
wz36  = Val("00000000.00")
wz46  = Val("00000000.00")
wz56  = Val("00000000.00")
wz66  = Val("00000000.00")
wz76  = Val("00000000.00")
wz86  = Val("00000000.00")
wz96  = Val("00000000.00")
wz106 = Val("00000000.00")
wz116 = Val("00000000.00")
wz126 = Val("00000000.00")
wz136 = Val("00000000.00")
wz146 = Val("00000000.00")
wz156 = Val("00000000.00")
wz166 = Val("00000000.00")
wz176 = Val("00000000.00")
wz186 = Val("00000000.00")
wz196 = Val("00000000.00")
wz206 = Val("00000000.00")
wz216 = Val("00000000.00")
wz226 = Val("00000000.00")
ZEZ   = 0
wper  = Val("0")

MainMask("ZBIROVI STAVKI UPLACENOG POREZA ZA KUMULATIV")

@ 2,10 SAY "OD 01.01. DO 31.03  UNETI  1"
@ 3,10 SAY "OD 01.04. DO 30.06  UNETI  2"
@ 4,10 SAY "OD 01.07. DO 30.09  UNETI  3"
@ 5,10 SAY "OD 01.10. DO 31.12  UNETI  4"
@ 6,10 SAY "OD 01.01. DO 31.12  UNETI  5"
@ 8,32 SAY "UNESITE ODLUKU " GET WPER PICTURE "9"
READ

IF Lastkey() = 27 .OR. WPER = 0
   CLOSE PLACP
   CLOSE KUMULUP
   RETURN
ENDIF

* ovde obezbediti sta ima u rezervama po nazivu
mREZ11 = Space(18)
mREZ22 = Space(18)
mREZ33 = Space(18)
DO WHILE ! Eof()
   IF rez11 = " "
      zez = zez + 0
   ELSE
      mREZ11 = REZ11
   ENDIF
   IF rez22 = " "
      zez = zez + 0
   ELSE
      mREZ22 = REZ22
   ENDIF
   IF rez33 = " "
      zez = zez + 0
   ELSE
      mREZ33 = REZ33
   ENDIF
   SKIP
ENDDO

* SELECT PLACP
GO TOP
* kraj obezbedjivanja po rezervama

* idem po zbirove
DO CASE
   CASE wper = 1
      WDAT1  = Date()
      WDAT11 = Date()
      WDAT2  = Date()
      WDAT22 = Date()
      WDAT3  = Date()
      WDAT33 = Date()
      WDAT4  = Date()
      WDAT44 = Date()
      WDAT5  = Date()
      WDAT55 = Date()
      WDAT6  = Date()
      WDAT66 = Date()
      WOD1A = "01.01."+Str(Year(Date()),4)
      WOD1 = CtoD(WOD1A)
      WDO1A = "15.01."+Str(Year(Date()),4)
      WDO1 = CtoD(WDO1A)
      WOD2A = "16.01."+Str(Year(Date()),4)
      WOD2 = CtoD(WOD2A)
      WDO2A = "31.01."+Str(Year(Date()),4)
      WDO2 = CtoD(WDO2A)
      WOD3A = "01.02."+Str(Year(Date()),4)
      WOD3 = CtoD(WOD3A)
      WDO3A = "15.02."+Str(Year(Date()),4)
      WDO3 = CtoD(WDO3A)
      WOD4A = "16.02."+Str(Year(Date()),4)
      WOD4 = CtoD(WOD4A)
      WDO4A = "28.02."+Str(Year(Date()),4)
      WDO4 = CtoD(WDO4A)
      WOD5A = "01.03."+Str(Year(Date()),4)
      WOD5 = CtoD(WOD5A)
      WDO5A = "15.03."+Str(Year(Date()),4)
      WDO5 = CtoD(WDO5A)
      WOD6A = "16.03."+Str(Year(Date()),4)
      WOD6 = CtoD(WOD6A)
      WDO6A = "31.03."+Str(Year(Date()),4)
      WDO6 = CtoD(WDO6A)

      DO WHILE ! Eof()
         IF dplacpor < wod1
            SKIP
            LOOP
         ENDIF

         IF dplacpor > wdo1
            SKIP
            LOOP
         ENDIF

         WDAT1 = DPLACPOR

         IF WDAT11 <> WDAT1
            WDAT11 = DPLACPOR
         ENDIF

         wz11  = Round(wz11 + PPOP73,2)
         wz21  = Round(wz21 + PPUS05,2)
         wz31  = Round(wz31 + PPNV46,2)
         wz41  = Round(wz41 + PPSREC81,2)
         wz51  = Round(wz51 + PPKPC03,2)
         wz61  = Round(wz61 + PORNDO22,2)
         wz71  = Round(wz71 + DOPVL43,2)
         wz81  = Round(wz81 + FINTRA50,2)
         wz91  = Round(wz91 + PORIM82,2)
         wz101 = Round(wz101 + PORSRE66,2)
         wz111 = Round(wz111 + PORPAU36,2)
         wz121 = Round(wz121 + GGZEM,2)
         wz131 = Round(wz131 + REZ1,2)
         wz141 = Round(wz141 + REZ2,2)
         wz151 = Round(wz151 + REZ3,2)
         wz161 = Round(wz161 + PPLEL80,2)
         wz171 = Round(wz171 + PPLEO87,2)
         wz181 = Round(wz181 + PPKOMU53,2)
         wz191 = Round(wz191 + PPFINU60,2)
         wz201 = Round(wz201 + PPUUT67,2)
         wz211 = Round(wz211 + PPUEST74,2)
         wz221 = Round(wz221 + PPUAUT88,2)

         SKIP
      ENDDO

      GO TOP
      DO WHILE ! Eof()
         IF dplacpor < wod2
            SKIP
            LOOP
         ENDIF

         IF dplacpor > wdo2
            SKIP
            LOOP
         ENDIF

         WDAT2 = DPLACPOR

         IF WDAT22 <> WDAT2
            WDAT22 = DPLACPOR
         ENDIF

         wz12  = Round(wz12 + PPOP73,2)
         wz22  = Round(wz22 + PPUS05,2)
         wz32  = Round(wz32 + PPNV46,2)
         wz42  = Round(wz42 + PPSREC81,2)
         wz52  = Round(wz52 + PPKPC03,2)
         wz62  = Round(wz62 + PORNDO22,2)
         wz72  = Round(wz72 + DOPVL43,2)
         wz82  = Round(wz82 + FINTRA50,2)
         wz92  = Round(wz92 + PORIM82,2)
         wz102 = Round(wz102 + PORSRE66,2)
         wz112 = Round(wz112 + PORPAU36,2)
         wz122 = Round(wz122 + GGZEM,2)
         wz132 = Round(wz132 + REZ1,2)
         wz142 = Round(wz142 + REZ2,2)
         wz152 = Round(wz152 + REZ3,2)
         wz162 = Round(wz162 + PPLEL80,2)
         wz172 = Round(wz172 + PPLEO87,2)
         wz182 = Round(wz182 + PPKOMU53,2)
         wz192 = Round(wz192 + PPFINU60,2)
         wz202 = Round(wz202 + PPUUT67,2)
         wz212 = Round(wz212 + PPUEST74,2)
         wz222 = Round(wz222 + PPUAUT88,2)

         SKIP
      ENDDO

      GO TOP
      DO WHILE ! Eof()
         IF dplacpor < wod3
            SKIP
            LOOP
         ENDIF

         IF dplacpor > wdo3
            SKIP
            LOOP
         ENDIF

         WDAT3 = DPLACPOR

         IF WDAT33 <> WDAT3
            WDAT33 = DPLACPOR
         ENDIF

         wz13  = Round(wz13 + PPOP73,2)
         wz23  = Round(wz23 + PPUS05,2)
         wz33  = Round(wz33 + PPNV46,2)
         wz43  = Round(wz43 + PPSREC81,2)
         wz53  = Round(wz53 + PPKPC03,2)
         wz63  = Round(wz63 + PORNDO22,2)
         wz73  = Round(wz73 + DOPVL43,2)
         wz83  = Round(wz83 + FINTRA50,2)
         wz93  = Round(wz93 + PORIM82,2)
         wz103 = Round(wz103 + PORSRE66,2)
         wz113 = Round(wz113 + PORPAU36,2)
         wz123 = Round(wz123 + GGZEM,2)
         wz133 = Round(wz133 + REZ1,2)
         wz143 = Round(wz143 + REZ2,2)
         wz153 = Round(wz153 + REZ3,2)
         wz163 = Round(wz163 + PPLEL80,2)
         wz173 = Round(wz173 + PPLEO87,2)
         wz183 = Round(wz183 + PPKOMU53,2)
         wz193 = Round(wz193 + PPFINU60,2)
         wz203 = Round(wz203 + PPUUT67,2)
         wz213 = Round(wz213 + PPUEST74,2)
         wz223 = Round(wz223 + PPUAUT88,2)

         SKIP
      ENDDO

      GO TOP
      DO WHILE ! Eof()
         IF dplacpor < wod4
            SKIP
            LOOP
         ENDIF

         IF dplacpor > wdo4
            SKIP
            LOOP
         ENDIF

         WDAT4 = DPLACPOR

         IF WDAT44 <> WDAT4
            WDAT44 = DPLACPOR
         ENDIF

         wz14  = Round(wz14 + PPOP73,2)
         wz24  = Round(wz24 + PPUS05,2)
         wz34  = Round(wz34 + PPNV46,2)
         wz44  = Round(wz44 + PPSREC81,2)
         wz54  = Round(wz54 + PPKPC03,2)
         wz64  = Round(wz64 + PORNDO22,2)
         wz74  = Round(wz74 + DOPVL43,2)
         wz84  = Round(wz84 + FINTRA50,2)
         wz94  = Round(wz94 + PORIM82,2)
         wz104 = Round(wz104 + PORSRE66,2)
         wz114 = Round(wz114 + PORPAU36,2)
         wz124 = Round(wz124 + GGZEM,2)
         wz134 = Round(wz134 + REZ1,2)
         wz144 = Round(wz144 + REZ2,2)
         wz154 = Round(wz154 + REZ3,2)
         wz164 = Round(wz164 + PPLEL80,2)
         wz174 = Round(wz174 + PPLEO87,2)
         wz184 = Round(wz184 + PPKOMU53,2)
         wz194 = Round(wz194 + PPFINU60,2)
         wz204 = Round(wz204 + PPUUT67,2)
         wz214 = Round(wz214 + PPUEST74,2)
         wz224 = Round(wz224 + PPUAUT88,2)

         SKIP
      ENDDO

      GO TOP
      DO WHILE ! Eof()
         IF dplacpor < wod5
            SKIP
            LOOP
         ENDIF

         IF dplacpor > wdo5
            SKIP
            LOOP
         ENDIF

         WDAT5 = DPLACPOR

         IF WDAT55 <> WDAT5
            WDAT55 = DPLACPOR
         ENDIF

         wz15  = Round(wz15 + PPOP73,2)
         wz25  = Round(wz25 + PPUS05,2)
         wz35  = Round(wz35 + PPNV46,2)
         wz45  = Round(wz45 + PPSREC81,2)
         wz55  = Round(wz55 + PPKPC03,2)
         wz65  = Round(wz65 + PORNDO22,2)
         wz75  = Round(wz75 + DOPVL43,2)
         wz85  = Round(wz85 + FINTRA50,2)
         wz95  = Round(wz95 + PORIM82,2)
         wz105 = Round(wz105 + PORSRE66,2)
         wz115 = Round(wz115 + PORPAU36,2)
         wz125 = Round(wz125 + GGZEM,2)
         wz135 = Round(wz135 + REZ1,2)
         wz145 = Round(wz145 + REZ2,2)
         wz155 = Round(wz155 + REZ3,2)
         wz165 = Round(wz165 + PPLEL80,2)
         wz175 = Round(wz175 + PPLEO87,2)
         wz185 = Round(wz185 + PPKOMU53,2)
         wz195 = Round(wz195 + PPFINU60,2)
         wz205 = Round(wz205 + PPUUT67,2)
         wz215 = Round(wz215 + PPUEST74,2)
         wz225 = Round(wz225 + PPUAUT88,2)

         SKIP
      ENDDO

      GO TOP
         DO WHILE ! Eof()
            IF dplacpor < wod6
               SKIP
               LOOP
            ENDIF

            IF dplacpor > wdo6
               SKIP
               LOOP
            ENDIF

            WDAT6 = DPLACPOR

            IF WDAT66 <> WDAT6
               WDAT66 = DPLACPOR
            ENDIF

            wz16  = Round(wz16 + PPOP73,2)
            wz26  = Round(wz26 + PPUS05,2)
            wz36  = Round(wz36 + PPNV46,2)
            wz46  = Round(wz46 + PPSREC81,2)
            wz56  = Round(wz56 + PPKPC03,2)
            wz66  = Round(wz66 + PORNDO22,2)
            wz76  = Round(wz76 + DOPVL43,2)
            wz86  = Round(wz86 + FINTRA50,2)
            wz96  = Round(wz96 + PORIM82,2)
            wz106 = Round(wz106 + PORSRE66,2)
            wz116 = Round(wz116 + PORPAU36,2)
            wz126 = Round(wz126 + GGZEM,2)
            wz136 = Round(wz136 + REZ1,2)
            wz146 = Round(wz146 + REZ2,2)
            wz156 = Round(wz156 + REZ3,2)
            wz166 = Round(wz166 + PPLEL80,2)
            wz176 = Round(wz176 + PPLEO87,2)
            wz186 = Round(wz186 + PPKOMU53,2)
            wz196 = Round(wz196 + PPFINU60,2)
            wz206 = Round(wz206 + PPUUT67,2)
            wz216 = Round(wz216 + PPUEST74,2)
            wz226 = Round(wz226 + PPUAUT88,2)

            SKIP
         ENDDO

         * upisati u kumulup dobijene zbirove i oznake i datume uplate
         SELECT KUMULUP
         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 1

         REPLACE PER1 WITH WZ11
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ12
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ13
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ14
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ15
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ16
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 2

         REPLACE PER1 WITH WZ161
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ162
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ163
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ164
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ165
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ166
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 3

         REPLACE PER1 WITH WZ171
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ172
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ173
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ174
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ175
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ176
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 4

         REPLACE PER1 WITH WZ51
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ52
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ53
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ54
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ55
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ56
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 5

         REPLACE PER1 WITH WZ31
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ32
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ33
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ34
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ35
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ36
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 6

         REPLACE PER1 WITH WZ181
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ182
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ183
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ184
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ185
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ186
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 7

         REPLACE PER1 WITH WZ191
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ192
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ193
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ194
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ195
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ196
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 8

         REPLACE PER1 WITH WZ201
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ202
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ203
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ204
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ205
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ206
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 9

         REPLACE PER1 WITH WZ211
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ212
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ213
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ214
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ215
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ216
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 10

         REPLACE PER1 WITH WZ41
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ42
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ43
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ44
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ45
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ46
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 11

         REPLACE PER1 WITH WZ221
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ222
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ223
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ224
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ225
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ226
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66

         APPEND BLANK
         REPLACE OZKUM WITH WPER
         REPLACE KUMPOZ WITH 12

         REPLACE PER1 WITH WZ21
         REPLACE DAT1 WITH WDAT1
         REPLACE DAT11 WITH WDAT11

         REPLACE PER2 WITH WZ22
         REPLACE DAT2 WITH WDAT2
         REPLACE DAT22 WITH WDAT22

         REPLACE PER3 WITH WZ23
         REPLACE DAT3 WITH WDAT3
         REPLACE DAT33 WITH WDAT33

         REPLACE PER4 WITH WZ24
         REPLACE DAT4 WITH WDAT4
         REPLACE DAT44 WITH WDAT44

         REPLACE PER5 WITH WZ25
         REPLACE DAT5 WITH WDAT5
         REPLACE DAT55 WITH WDAT55

         REPLACE PER6 WITH WZ26
         REPLACE DAT6 WITH WDAT6
         REPLACE DAT66 WITH WDAT66
         * kraj upisivanja u kumulup za period
ENDCASE
* kraj idem po zbirove

CLOSE PLACP
CLOSE KUMULUP

RETURN
